/*
	This file is a node.js module intended for use in different UDF datafeeds.
*/
//	This list should contain all the symbosl available through your datafeed.
//	The current version is extremely incomplete (as it's just a sample): Yahoo has much more of them.


var symbols = [
/*{ name: "^GDAXI", description:"DAX", exchange:"XETRA", type:"index" },
{ name: "^NSEI", description:"CNX NIFTY", exchange:"NSE", type:"index" },
{ name: "A", description:"Agilent Technologies Inc.", exchange:"NYSE", type:"stock" },
{ name: "AA", description:"Alcoa Inc.", exchange:"NYSE", type:"stock" },
{ name: "AAL", description:"American Airlines Group Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "AAPL", description:"Apple Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "ABB", description:"ABB Ltd.", exchange:"NYSE", type:"stock" },
{ name: "ABBV", description:"AbbVie Inc.", exchange:"NYSE", type:"stock" },
{ name: "ABT", description:"Abbott Laboratories", exchange:"NYSE", type:"stock" },
{ name: "ABX", description:"Barrick Gold Corporation", exchange:"NYSE", type:"stock" },
{ name: "ACHN", description:"Achillion Pharmaceuticals, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "ACI", description:"Arch Coal Inc.", exchange:"NYSE", type:"stock" },
{ name: "ACN", description:"Accenture plc", exchange:"NYSE", type:"stock" },
{ name: "ACT", description:"Actavis plc", exchange:"NYSE", type:"stock" },
{ name: "ADBE", description:"Adobe Systems Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "ADSK", description:"Autodesk, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "AEO", description:"American Eagle Outfitters, Inc.", exchange:"NYSE", type:"stock" },
{ name: "AGNC", description:"American Capital Agency Corp.", exchange:"NasdaqNM", type:"stock" },
{ name: "AIG", description:"American International Group, Inc.", exchange:"NYSE", type:"stock" },
{ name: "AKAM", description:"Akamai Technologies, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "ALU", description:"Alcatel-Lucent", exchange:"NYSE", type:"stock" },
{ name: "ALXN", description:"Alexion Pharmaceuticals, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "AMAT", description:"Applied Materials, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "AMD", description:"Advanced Micro Devices, Inc.", exchange:"NYSE", type:"stock" },
{ name: "AMGN", description:"Amgen Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "AMZN", description:"Amazon.com Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "ANF", description:"Abercrombie & Fitch Co.", exchange:"NYSE", type:"stock" },
{ name: "ANR", description:"Alpha Natural Resources, Inc.", exchange:"NYSE", type:"stock" },
{ name: "APA", description:"Apache Corp.", exchange:"NYSE", type:"stock" },
{ name: "APC", description:"Anadarko Petroleum Corporation", exchange:"NYSE", type:"stock" },
{ name: "ARC", description:"ARC Document Solutions, Inc.", exchange:"NYSE", type:"stock" },
{ name: "ARIA", description:"Ariad Pharmaceuticals Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "ARNA", description:"Arena Pharmaceuticals, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "ARR", description:"ARMOUR Residential REIT, Inc.", exchange:"NYSE", type:"stock" },
{ name: "AUXL", description:"Auxilium Pharmaceuticals Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "AVGO", description:"Avago Technologies Limited", exchange:"NasdaqNM", type:"stock" },
{ name: "AVNR", description:"Avanir Pharmaceuticals, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "AWAY", description:"HomeAway, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "AXP", description:"American Express Company", exchange:"NYSE", type:"stock" },
{ name: "AZO", description:"AutoZone, Inc.", exchange:"NYSE", type:"stock" },
{ name: "BA", description:"The Boeing Company", exchange:"NYSE", type:"stock" },
{ name: "BAC", description:"Bank of America Corporation", exchange:"NYSE", type:"stock" },
{ name: "BAX", description:"Baxter International Inc.", exchange:"NYSE", type:"stock" },
{ name: "BBBY", description:"Bed Bath & Beyond Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "BBRY", description:"BlackBerry Limited", exchange:"NasdaqNM", type:"stock" },
{ name: "BBT", description:"BB&T Corporation", exchange:"NYSE", type:"stock" },
{ name: "BBY", description:"Best Buy Co., Inc.", exchange:"NYSE", type:"stock" },
{ name: "BIDU", description:"Baidu, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "BIIB", description:"Biogen Idec Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "BK", description:"The Bank of New York Mellon Corporation", exchange:"NYSE", type:"stock" },
{ name: "BLK", description:"BlackRock, Inc.", exchange:"NYSE", type:"stock" },
{ name: "BMO", description:"Bank of Montreal", exchange:"NYSE", type:"stock" },
{ name: "BMY", description:"Bristol-Myers Squibb Company", exchange:"NYSE", type:"stock" },
{ name: "BP", description:"BP plc", exchange:"NYSE", type:"stock" },
{ name: "BRCD", description:"Brocade Communications Systems, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "BRCM", description:"Broadcom Corp.", exchange:"NasdaqNM", type:"stock" },
{ name: "BRK-B", description:"Berkshire Hathaway Inc.", exchange:"NYSE", type:"stock" },
{ name: "BTU", description:"Peabody Energy Corp.", exchange:"NYSE", type:"stock" },
{ name: "BX", description:"The Blackstone Group L.P.", exchange:"NYSE", type:"stock" },
{ name: "C", description:"Citigroup Inc.", exchange:"NYSE", type:"stock" },
{ name: "CHK", description:"Chesapeake Energy Corporation", exchange:"NYSE", type:"stock" },
{ name: "CII.TA", description:"", exchange:"Tel Aviv", type:"stock" },
{ name: "CNP", description:"CenterPoint Energy, Inc.", exchange:"NYSE", type:"stock" },
{ name: "COLE", description:"Cole Real Estate Investments, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "CSCO", description:"Cisco Systems, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "D", description:"Dominion Resources, Inc.", exchange:"NYSE", type:"stock" },
{ name: "DAL", description:"Delta Air Lines Inc.", exchange:"NYSE", type:"stock" },
{ name: "DANG", description:"E-Commerce China Dangdang Inc.", exchange:"NYSE", type:"stock" },
{ name: "DBD", description:"Diebold, Incorporated", exchange:"NYSE", type:"stock" },
{ name: "DCM", description:"NTT DOCOMO, Inc.", exchange:"NYSE", type:"stock" },
{ name: "DD", description:"E. I. du Pont de Nemours and Company", exchange:"NYSE", type:"stock" },
{ name: "DDD", description:"3D Systems Corp.", exchange:"NYSE", type:"stock" },
{ name: "DE", description:"Deere & Company", exchange:"NYSE", type:"stock" },
{ name: "DE.AS", description:"", exchange:"Amsterdam", type:"stock" },
{ name: "DECK", description:"Deckers Outdoor Corp.", exchange:"NYSE", type:"stock" },
{ name: "DEI", description:"Douglas Emmett Inc", exchange:"NYSE", type:"stock" },
{ name: "DHI", description:"DR Horton Inc.", exchange:"NYSE", type:"stock" },
{ name: "DIS", description:"The Walt Disney Company", exchange:"NYSE", type:"stock" },
{ name: "DLTR", description:"Dollar Tree, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "DNDN", description:"Dendreon Corp.", exchange:"NasdaqNM", type:"stock" },
{ name: "DO", description:"Diamond Offshore Drilling, Inc.", exchange:"NYSE", type:"stock" },
{ name: "DOV", description:"Dover Corporation", exchange:"NYSE", type:"stock" },
{ name: "DOW", description:"The Dow Chemical Company", exchange:"NYSE", type:"stock" },
{ name: "DPM", description:"DCP Midstream Partners LP", exchange:"NYSE", type:"stock" },
{ name: "DRI", description:"Darden Restaurants, Inc.", exchange:"NYSE", type:"stock" },
{ name: "DRX.IR", description:"", exchange:"Irish", type:"stock" },
{ name: "DRYS", description:"DryShips, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "DV", description:"DeVry Education Group Inc.", exchange:"NYSE", type:"stock" },
{ name: "DVN", description:"Devon Energy Corporation", exchange:"NYSE", type:"stock" },
{ name: "EA", description:"Electronic Arts Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "EBAY", description:"eBay Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "EBIX", description:"Ebix Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "ECYT", description:"Endocyte, Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "ED", description:"Consolidated Edison, Inc.", exchange:"NYSE", type:"stock" },
{ name: "EMC", description:"EMC Corporation", exchange:"NYSE", type:"stock" },
{ name: "ENT", description:"Global Eagle Entertainment Inc.", exchange:"NCM", type:"stock" },
{ name: "ESI", description:"ITT Educational Services Inc.", exchange:"NYSE", type:"stock" },
{ name: "ESRX", description:"Express Scripts Holding Company", exchange:"NasdaqNM", type:"stock" },
{ name: "ETFC", description:"E*TRADE Financial Corporation", exchange:"NasdaqNM", type:"stock" },
{ name: "ETP", description:"Energy Transfer Partners, L.P.", exchange:"NYSE", type:"stock" },
{ name: "EXC", description:"Exelon Corporation", exchange:"NYSE", type:"stock" },
{ name: "EXPE", description:"Expedia Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "EZCH", description:"EZchip Semiconductor Ltd.", exchange:"NasdaqNM", type:"stock" },
{ name: "F", description:"Ford Motor Co.", exchange:"NYSE", type:"stock" },
{ name: "FCEL", description:"FuelCell Energy Inc.", exchange:"NGM", type:"stock" },
{ name: "FRE.AX", description:"Freshtel Holdings Limited", exchange:"ASX", type:"stock" },
{ name: "GALE", description:"Galena Biopharma, Inc.", exchange:"NCM", type:"stock" },
{ name: "GD", description:"General Dynamics Corp.", exchange:"NYSE", type:"stock" },
{ name: "GE", description:"General Electric Company", exchange:"NYSE", type:"stock" },
{ name: "GTAT", description:"GT Advanced Technologies Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "HD", description:"The Home Depot, Inc.", exchange:"NYSE", type:"stock" },
{ name: "IBM", description:"International Business Machines Corporation", exchange:"NYSE", type:"stock" },
{ name: "INTC", description:"Intel Corporation", exchange:"NasdaqNM", type:"stock" },
{ name: "JPM", description:"JPMorgan Chase & Co.", exchange:"NYSE", type:"stock" },
{ name: "KERX", description:"Keryx Biopharmaceuticals Inc.", exchange:"NCM", type:"stock" },
{ name: "KMP", description:"Kinder Morgan Energy Partners, L.P.", exchange:"NYSE", type:"stock" },
{ name: "KO", description:"The Coca-Cola Company", exchange:"NYSE", type:"stock" },
{ name: "LINE", description:"Linn Energy, LLC", exchange:"NasdaqNM", type:"stock" },
{ name: "LLY", description:"Eli Lilly and Company", exchange:"NYSE", type:"stock" },
{ name: "LULU", description:"Lululemon Athletica Inc.", exchange:"NasdaqNM", type:"stock" },
{ name: "LUV", description:"Southwest Airlines Co.", exchange:"NYSE", type:"stock" },
{ name: "LYG", description:"Lloyds Banking Group plc", exchange:"NYSE", type:"stock" },
{ name: "MCD", description:"McDonald's Corp.", exchange:"NYSE", type:"stock" },
{ name: "MNST", description:"Monster Beverage Corporation", exchange:"NasdaqNM", type:"stock" },
{ name: "MO", description:"Altria Group Inc.", exchange:"NYSE", type:"stock" },
{ name: "MPEL", description:"Melco Crown Entertainment Limited", exchange:"NasdaqNM", type:"stock" },
{ name: "MSFT", description:"Microsoft Corporation", exchange:"NasdaqNM", type:"stock" },
{ name: "NLY", description:"Annaly Capital Management, Inc.", exchange:"NYSE", type:"stock" },
{ name: "NUS", description:"Nu Skin Enterprises Inc.", exchange:"NYSE", type:"stock" },
{ name: "OLED", description:"Universal Display Corp.", exchange:"NasdaqNM", type:"stock" },
{ name: "PNRA", description:"Panera Bread Company", exchange:"NasdaqNM", type:"stock" },
{ name: "PRAN", description:"Prana Biotechnology Limited", exchange:"NCM", type:"stock" },
{ name: "RAD", description:"Rite Aid Corporation", exchange:"NYSE", type:"stock" },
{ name: "SAM", description:"Boston Beer Co. Inc.", exchange:"NYSE", type:"stock" },
{ name: "SAN", description:"Banco Santander, S.A.", exchange:"NYSE", type:"stock" },
{ name: "SCTY", description:"SolarCity Corporation", exchange:"NasdaqNM", type:"stock" },
{ name: "SD", description:"SandRidge Energy, Inc.", exchange:"NYSE", type:"stock" },
{ name: "STZ", description:"Constellation Brands Inc.", exchange:"NYSE", type:"stock" },
{ name: "SU", description:"Suncor Energy Inc.", exchange:"NYSE", type:"stock" },
{ name: "T", description:"AT&T, Inc.", exchange:"NYSE", type:"stock" },
{ name: "TEG.AX", description:"Triangle Energy (Global) Limited", exchange:"ASX", type:"stock" },
{ name: "TTW.V", description:"TIMES THREE WIRELESS INC", exchange:"CDNX", type:"stock" },
{ name: "UA", description:"Under Armour, Inc.", exchange:"NYSE", type:"stock" },
{ name: "UCD.SG", description:"UC RESOURCES", exchange:"Stuttgart", type:"stock" },
{ name: "USB", description:"U.S. Bancorp", exchange:"NYSE", type:"stock" },
{ name: "VLG.MC", description:"", exchange:"NYSE", type:"stock" },
{ name: "VZ", description:"Verizon Communications Inc.", exchange:"NYSE", type:"stock" },
{ name: "WDC", description:"Western Digital Corporation", exchange:"NasdaqNM", type:"stock" },
{ name: "WFC", description:"Wells Fargo & Company", exchange:"NYSE", type:"stock" },
{ name: "WLT", description:"Walter Energy, Inc.", exchange:"NYSE", type:"stock" },
{ name: "XOM", description:"Exxon Mobil Corporation", exchange:"NYSE", type:"stock" },
*/
{name:"AFG.OL",description:"AF Group",exchange:"OB",type:"stock"},
{name:"AGA.OL",description:"Agasti Holding",exchange:"OB",type:"stock"},
{name:"AKA.OL ",description:"Akastor",exchange:"OB",type:"stock"},
{name:"AKER.OL",description:"Aker",exchange:"OB",type:"stock"},
{name:"AKSO.OL",description:"Aker Solutions",exchange:"OB",type:"stock"},
{name:"AKVA.OL",description:"AKVA Group",exchange:"OB",type:"stock"},
{name:"AMSC.OL",description:"American Shipping Company",exchange:"OB",type:"stock"},
{name:"APP.OL",description:"Apptix",exchange:"OB",type:"stock"},
{name:"AQUA.OL",description:"Aqualis",exchange:"OB",type:"stock"},
{name:"ARCHER.OL",description:"Archer",exchange:"OB",type:"stock"},
{name:"AFK.OL",description:"Arendals Fossekompani",exchange:"OB",type:"stock"},
{name:"ASETEK.OL",description:"Asetek",exchange:"OB",type:"stock"},
{name:"ATEA.OL",description:"Atea",exchange:"OB",type:"stock"},
{name:"ATLA+NOK.OL",description:"Atlantic Petroleum",exchange:"OB",type:"stock"},
{name:"AURG.OL",description:"Aurskog Sparebank*",exchange:"OB",type:"stock"},
{name:"AUSS.OL",description:"Austevoll Seafood",exchange:"OB",type:"stock"},
{name:"AVANCE.OL",description:"Avance Gas Holding",exchange:"OB",type:"stock"},
{name:"AVM.OL",description:"Avocet Mining",exchange:"OB",type:"stock"},
{name:"AXA.OL",description:"Axactor",exchange:"OB",type:"stock"},
{name:"BAKKA.OL",description:"Bakkafrost",exchange:"OB",type:"stock"},
{name:"BEL.OL",description:"Belships",exchange:"OB",type:"stock"},
{name:"BERGEN.OL",description:"Bergen Group",exchange:"OB",type:"stock"},
{name:"BIONOR.OL",description:"Bionor Pharma",exchange:"OB",type:"stock"},
{name:"BIOTEC.OL",description:"Biotec Pharmacon",exchange:"OB",type:"stock"},
{name:"BIRD.OL",description:"Birdstep Technology",exchange:"OB",type:"stock"},
{name:"BON.OL",description:"Bonheur",exchange:"OB",type:"stock"},
{name:"BOR.OL",description:"Borgestad",exchange:"OB",type:"stock"},
{name:"BRG.OL",description:"Borregaard",exchange:"OB",type:"stock"},
{name:"BOUVET.OL",description:"Bouvet ASA",exchange:"OB",type:"stock"},
{name:"BWLPG.OL",description:"BW LPG",exchange:"OB",type:"stock"},
{name:"BWO.OL",description:"BW Offshore Limited",exchange:"OB",type:"stock"},
{name:"BMA.OL",description:"Byggma",exchange:"OB",type:"stock"},
{name:"COV.OL",description:"ContextVision",exchange:"OB",type:"stock"},
{name:"DAT.OL",description:"Data Respons",exchange:"OB",type:"stock"},
{name:"DESSC.OL",description:"Deep Sea Supply",exchange:"OB",type:"stock"},
{name:"DETNOR.OL",description:"Det Norske Oljeselskap ASA",exchange:"OB",type:"stock"},
{name:"DNB.OL",description:"DNB ASA",exchange:"OB",type:"stock"},
{name:"DNO.OL",description:"DNO International",exchange:"OB",type:"stock"},
{name:"DOF.OL",description:"DOF ASA",exchange:"OB",type:"stock"},
{name:"EIOF.OL",description:"Eidesvik Offshore",exchange:"OB",type:"stock"},
{name:"EKO.OL",description:"Ekornes",exchange:"OB",type:"stock"},
{name:"EMGS.OL",description:"Electromagnetic Geoservices",exchange:"OB",type:"stock"},
{name:"EMAS.OL",description:"EMAS Offshore",exchange:"OB",type:"stock"},
{name:"ENTRA.OL",description:"Entra",exchange:"OB",type:"stock"},
{name:"EPR.OL",description:"Europris",exchange:"OB",type:"stock"},
{name:"FAR.OL",description:"Farstad Shipping",exchange:"OB",type:"stock"},
{name:"FOE.OL",description:"Fred. Olsen Energy",exchange:"OB",type:"stock"},
{name:"FRO.OL",description:"Frontline Ltd.",exchange:"OB",type:"stock"},
{name:"FUNCOM.OL",description:"Funcom",exchange:"OB",type:"stock"},
{name:"GIG.OL",description:"Gaming Innovation Group",exchange:"OB",type:"stock"},
{name:"GRO.OL",description:"Ganger Rolf ASA",exchange:"OB",type:"stock"},
{name:"RISH.OL",description:"GC Rieber Shipping",exchange:"OB",type:"stock"},
{name:"GJF.OL",description:"Gjensidige Forsikring",exchange:"OB",type:"stock"},
{name:"GOGL.OL",description:"Golden Ocean Group",exchange:"OB",type:"stock"},
{name:"GOD.OL",description:"Goodtech",exchange:"OB",type:"stock"},
{name:"GSF.OL",description:"Grieg Seafood",exchange:"OB",type:"stock"},
{name:"GYL.OL",description:"Gyldendal ASA",exchange:"OB",type:"stock"},
{name:"HLNG.OL",description:"Höegh LNG Holdings",exchange:"OB",type:"stock"},
{name:"HNA.OL",description:"Hafslund ser. A",exchange:"OB",type:"stock"},
{name:"HNB.OL",description:"Hafslund ser. B",exchange:"OB",type:"stock"},
{name:"HFISK.OL",description:"Havfisk",exchange:"OB",type:"stock"},
{name:"HAVI.OL",description:"Havila Shipping",exchange:"OB",type:"stock"},
{name:"HYARD.OL",description:"Havyard Group",exchange:"OB",type:"stock"},
{name:"HELG.OL",description:"Helgeland Sparebank*",exchange:"OB",type:"stock"},
{name:"HEX.OL",description:"Hexagon Composites",exchange:"OB",type:"stock"},
{name:"HSPG.OL",description:"Høland og Setskog Sparebank*",exchange:"OB",type:"stock"},
{name:"IMSK.OL",description:"I.M. Skaugen",exchange:"OB",type:"stock"},
{name:"IDEX.OL",description:"IDEX ASA",exchange:"OB",type:"stock"},
{name:"IOX.OL",description:"InterOil Exploration and Production",exchange:"OB",type:"stock"},
{name:"ISSG.OL",description:"Indre Sogn Sparebank*",exchange:"OB",type:"stock"},
{name:"ITX.OL",description:"Intex Resources",exchange:"OB",type:"stock"},
{name:"ITE.OL",description:"Itera",exchange:"OB",type:"stock"},
{name:"JIN.OL",description:"Jinhui Shipping and Transportation",exchange:"OB",type:"stock"},
{name:"JAEREN.OL",description:"Jæren Sparebank*",exchange:"OB",type:"stock"},
{name:"KID.OL",description:"Kid",exchange:"OB",type:"stock"},
{name:"KIT.OL",description:"Kitron",exchange:"OB",type:"stock"},
{name:"KOA.OL",description:"Kongsberg Automotive",exchange:"OB",type:"stock"},
{name:"KOG.OL",description:"Kongsberg Gruppen",exchange:"OB",type:"stock"},
{name:"KVAER.OL",description:"Kværner",exchange:"OB",type:"stock"},
{name:"LSG.OL",description:"Lerøy Seafood Group",exchange:"OB",type:"stock"},
{name:"MHG.OL",description:"Marine Harvest",exchange:"OB",type:"stock"},
{name:"MEDI.OL",description:"Medistim",exchange:"OB",type:"stock"},
{name:"MELG.OL",description:"Melhus Sparebank*",exchange:"OB",type:"stock"},
{name:"MULTI.OL",description:"Multiconsult",exchange:"OB",type:"stock"},
{name:"NAPA.OL",description:"Napatech",exchange:"OB",type:"stock"},
{name:"NAVA.OL",description:"Navamedic",exchange:"OB",type:"stock"},
{name:"NEL.OL",description:"NEL Hydrogen",exchange:"OB",type:"stock"},
{name:"NGT.OL",description:"NextGenTel Holding",exchange:"OB",type:"stock"},
{name:"NEXT.OL",description:"NEXT Biometrics Group",exchange:"OB",type:"stock"},
{name:"NANO.OL",description:"Nordic Nanovector",exchange:"OB",type:"stock"},
{name:"NOD.OL",description:"Nordic Semiconductor",exchange:"OB",type:"stock"},
{name:"NHY.OL",description:"Norsk Hydro",exchange:"OB",type:"stock"},
{name:"NSG.OL",description:"Norske Skog",exchange:"OB",type:"stock"},
{name:"NOF.OL",description:"Northern Offshore",exchange:"OB",type:"stock"},
{name:"NRS.OL",description:"Norway Royal Salmon",exchange:"OB",type:"stock"},
{name:"NAS.OL",description:"Norwegian Air Shuttle",exchange:"OB",type:"stock"},
{name:"NOR.OL",description:"Norwegian Energy Company",exchange:"OB",type:"stock"},
{name:"NPRO.OL",description:"Norwegian Property",exchange:"OB",type:"stock"},
{name:"NRC.OL",description:"NRC Group",exchange:"OB",type:"stock"},
{name:"NTS.OL",description:"NTS ASA",exchange:"OB",type:"stock"},
{name:"OCY.OL",description:"Ocean Yield",exchange:"OB",type:"stock"},
{name:"OTS.OL",description:"Oceanteam Shipping",exchange:"OB",type:"stock"},
{name:"ODL.OL",description:"Odfjell Drilling",exchange:"OB",type:"stock"},
{name:"ODF.OL",description:"Odfjell ser. A",exchange:"OB",type:"stock"},
{name:"ODFB.OL",description:"Odfjell ser. B",exchange:"OB",type:"stock"},
{name:"OLT.OL",description:"Olav Thon Eiendomsselskap",exchange:"OB",type:"stock"},
{name:"OPERA.OL",description:"Opera Software",exchange:"OB",type:"stock"},
{name:"ORK.OL",description:"Orkla Group",exchange:"OB",type:"stock"},
{name:"PEN.OL",description:"Panoro Energy",exchange:"OB",type:"stock"},
{name:"PGS.OL",description:"Petroleum Geo-Services",exchange:"OB",type:"stock"},
{name:"PDR.OL",description:"Petrolia",exchange:"OB",type:"stock"},
{name:"PHO.OL",description:"Photocure",exchange:"OB",type:"stock"},
{name:"PLCS.OL",description:"Polarcus",exchange:"OB",type:"stock"},
{name:"POL.OL",description:"Polaris Media",exchange:"OB",type:"stock"},
{name:"PRS.OL",description:"Prosafe",exchange:"OB",type:"stock"},
{name:"PROTCT.OL",description:"Protector Forsikring",exchange:"OB",type:"stock"},
{name:"QFR.OL",description:"Q-Free",exchange:"OB",type:"stock"},
{name:"QEC.OL",description:"Questerre Energy Corporation",exchange:"OB",type:"stock"},
{name:"RAKP.OL",description:"RAK Petroleum",exchange:"OB",type:"stock"},
{name:"REACH.OL",description:"Reach Subsea",exchange:"OB",type:"stock"},
{name:"REC.OL",description:"REC Silicon",exchange:"OB",type:"stock"},
{name:"RENO.OL",description:"RenoNorden",exchange:"OB",type:"stock"},
{name:"RCL.OL",description:"Royal Caribbean Cruises",exchange:"OB",type:"stock"},
{name:"SALM.OL",description:"SalMar",exchange:"OB",type:"stock"},
{name:"SADG.OL",description:"Sandnes Sparebank*",exchange:"OB",type:"stock"},
{name:"SAS+NOK.OL",description:"SAS Group",exchange:"OB",type:"stock"},
{name:"SCI.OL",description:"Scana Industrier",exchange:"OB",type:"stock"},
{name:"SSO.OL",description:"Scatec Solar",exchange:"OB",type:"stock"},
{name:"SCH.OL",description:"Schibsted ser. A",exchange:"OB",type:"stock"},
{name:"SCH.OL",description:"Schibsted ser. B",exchange:"OB",type:"stock"},
{name:"SSC.OL",description:"The Scottish Salmon Company",exchange:"OB",type:"stock"},
{name:"SBX.OL",description:"SeaBird Exploration",exchange:"OB",type:"stock"},
{name:"SDRL.OL",description:"Seadrill",exchange:"OB",type:"stock"},
{name:"SBO.OL",description:"Selvaag Bolig",exchange:"OB",type:"stock"},
{name:"SEVDR.OL",description:"Sevan Drilling",exchange:"OB",type:"stock"},
{name:"SEVAN.OL",description:"Sevan Marine",exchange:"OB",type:"stock"},
{name:"SIOFF.OL",description:"Siem Offshore",exchange:"OB",type:"stock"},
{name:"SSI.OL",description:"Siem Shipping",exchange:"OB",type:"stock"},
{name:"SKBN.OL",description:"Skandiabanken ASA",exchange:"OB",type:"stock"},
{name:"SKI.OL",description:"Skiens Aktiemølle",exchange:"OB",type:"stock"},
{name:"SKUE.OL",description:"Skue Sparebank*",exchange:"OB",type:"stock"},
{name:"SOFF.OL",description:"Solstad Offshore",exchange:"OB",type:"stock"},
{name:"SOLV.OL",description:"Solvang",exchange:"OB",type:"stock"},
{name:"SONG.OL",description:"Songa Offshore",exchange:"OB",type:"stock"},
{name:"SBVG.OL",description:"SpareBank 1 BV*",exchange:"OB",type:"stock"},
{name:"NONG.OL",description:"SpareBank 1 Nord–Norge*",exchange:"OB",type:"stock"},
{name:"NTSG.OL",description:"SpareBank 1 Nøtterøy–Tønsberg*",exchange:"OB",type:"stock"},
{name:"RING.OL",description:"SpareBank 1 Ringerike Hadeland*",exchange:"OB",type:"stock"},
{name:"MING.OL",description:"SpareBank 1 SMN*",exchange:"OB",type:"stock"},
{name:"SRBANK.OL",description:"SpareBank 1 SR-Bank",exchange:"OB",type:"stock"},
{name:"SOAG.OL",description:"SpareBank 1 Østfold Akershus*",exchange:"OB",type:"stock"},
{name:"MORG.OL",description:"Sparebanken Møre*",exchange:"OB",type:"stock"},
{name:"SOR.OL",description:"Sparebanken Sør*",exchange:"OB",type:"stock"},
{name:"SVEG.OL",description:"Sparebanken Vest*",exchange:"OB",type:"stock"},
{name:"SPOG.OL",description:"Sparebanken Øst*",exchange:"OB",type:"stock"},
{name:"SPU.OL",description:"Spectrum",exchange:"OB",type:"stock"},
{name:"STL.OL",description:"Statoil",exchange:"OB",type:"stock"},
{name:"SNI.OL",description:"Stolt-Nielsen",exchange:"OB",type:"stock"},
{name:"STB.OL",description:"Storebrand",exchange:"OB",type:"stock"},
{name:"STORM.OL",description:"Storm Real Estate",exchange:"OB",type:"stock"},
{name:"STRONG.OL",description:"StrongPoint",exchange:"OB",type:"stock"},
{name:"SUBC.OL",description:"Subsea 7",exchange:"OB",type:"stock"},
{name:"TIL.OL",description:"Tanker Investments",exchange:"OB",type:"stock"},
{name:"TEAM.OL",description:"Team Tankers International",exchange:"OB",type:"stock"},
{name:"TEL.OL",description:"Telenor",exchange:"OB",type:"stock"},
{name:"TGS.OL",description:"TGS-NOPEC Geophysical Company",exchange:"OB",type:"stock"},
{name:"THIN.OL",description:"Thin Film Electronics ASA",exchange:"OB",type:"stock"},
{name:"TIDE.OL",description:"TIDE",exchange:"OB",type:"stock"},
{name:"TOM.OL",description:"Tomra Systems",exchange:"OB",type:"stock"},
{name:"TOTG.OL",description:"Totens Sparebank*",exchange:"OB",type:"stock"},
{name:"TTS.OL",description:"TTS Group",exchange:"OB",type:"stock"},
{name:"VARDIA.OL",description:"Vardia Insurance Group",exchange:"OB",type:"stock"},
{name:"VEI.OL",description:"Veidekke",exchange:"OB",type:"stock"},
{name:"VVL.OL",description:"Voss Veksel- og Landmandsbank",exchange:"OB",type:"stock"},
{name:"WEIFA.OL",description:"Weifa",exchange:"OB",type:"stock"},
{name:"WRL.OL",description:"Wentworth Resources",exchange:"OB",type:"stock"},
{name:"WBULK.OL",description:"Western Bulk",exchange:"OB",type:"stock"},
{name:"WWASA.OL",description:"Wilh. Wilhelmsen",exchange:"OB",type:"stock"},
{name:"WWI.OL",description:"Wilh. Wilhelmsen Holding ser. A",exchange:"OB",type:"stock"},
{name:"WWIB.OL",description:"Wilh. Wilhelmsen Holding ser. B",exchange:"OB",type:"stock"},
{name:"WILS.OL",description:"Wilson",exchange:"OB",type:"stock"},
{name:"XXL.OL",description:"XXL",exchange:"OB",type:"stock"},
{name:"YAR.OL",description:"Yara International",exchange:"OB",type:"stock"},
{name:"ZAL.OL",description:"Zalaris",exchange:"OB",type:"stock"}

];


function searchResultFromDatabaseItem(item) {
	return {
		symbol: item.name,
		full_name: item.name,
		description: item.description,
		exchange: item.exchange,
		type: item.type
	};
}


exports.search = function (searchString, type, exchange, maxRecords) {
	var MAX_SEARCH_RESULTS = !!maxRecords ? maxRecords : 50;
	var results = []; // array of WeightedItem { item, weight }
	var queryIsEmpty = !searchString || searchString.length == 0;
	var searchStringUpperCase = searchString.toUpperCase();

	for (var i = 0; i < symbols.length; ++i) {
		var item = symbols[i];

		if (type && type.length > 0 && item.type != type) {
			continue;
		}
		if (exchange && exchange.length > 0 && item.exchange != exchange) {
			continue;
		}

		var positionInName = item.name.toUpperCase().indexOf(searchStringUpperCase);
		var positionInDescription = item.description.toUpperCase().indexOf(searchStringUpperCase);

		if (queryIsEmpty || positionInName >= 0 || positionInDescription >= 0) {
			var found = false;
			for (var resultIndex = 0; resultIndex < results.length; resultIndex++) {
				if (results[resultIndex].item == item) {
					found = true;
					break;
				}
			}
			if (!found) {
				var weight = positionInName >= 0 ? positionInName : 8000 + positionInDescription;
				results.push({ item: item, weight: weight });
			}
		}
	}

	return results
		.sort(function (weightedItem1, weightedItem2) { return weightedItem1.weight - weightedItem2.weight; })
		.map(function (weightedItem) { return searchResultFromDatabaseItem(weightedItem.item); })
		.slice(0, Math.min(results.length, MAX_SEARCH_RESULTS));
}


exports.symbolInfo = function (symbolName) {

	var data = symbolName.split(':');
	var exchange = (data.length > 1 ? data[0] : "").toUpperCase();
	var symbol = (data.length > 1 ? data[1] : symbolName).toUpperCase();

	for (var i = 0; i < symbols.length; ++i) {
		var item = symbols[i];

		if (item.name.toUpperCase() == symbol && (exchange.length == 0 || exchange == item.exchange.toUpperCase())) {
			return item;
		}
	}

	return null;
}
